image: maven:latest
#build : 
#  stage: build
 # script: 
  #        - echo "just tezst for mvn compile"
   #       - mvn compile
#test: 
 # stage: test
  #script: 
   #       - echo "just tezst for mvn compile"
    #      - mvn clean test -e switch
          
maven-build:
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
      
      
      
      
#      clean:
 # stage: build

  #script:

   # - mvn clean package
    
#build-image:
 # stage: build-image
  #script:
   # - echo "Building Docker Image..."
    #- docker build -t dockerfileapp .