#image: maven:latest
stages:
  - build

#clean:
 # stage: build

  #script:

    #- mvn clean packag
    
build-image:
  stage: build-image
  script:
    - echo "Building Docker Image..."
    - docker build -t dockerfileapp .